In [1]:
from classic_fib import FibCode
import numpy as np 
import copy

L = 8 
start_arr = np.zeros(L, dtype=int)
codeword = FibCode.generate_init_code_word(L)
print("codeword")
print(codeword)
print()


error_board = copy.deepcopy(codeword)
offset = 0 
width = L//4
error_board[:,offset:width + offset] = 1
print("error board")
print(error_board)

codeword
[[1 1 0 1 0 1 1 0]
 [0 1 0 1 0 1 0 0]
 [0 0 1 1 1 0 0 0]
 [0 0 0 1 0 0 0 0]]

error board
[[1 1 0 1 0 1 1 0]
 [1 1 0 1 0 1 0 0]
 [1 1 1 1 1 0 0 0]
 [1 1 0 1 0 0 0 0]]


In [2]:
f = FibCode(L=L, original_code_board=codeword, original_errors_board=error_board)

In [3]:
res, info = f.decode_fib_code()

In [4]:
res

'yay! success'

In [5]:
info

[0,
 array([1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 'hori']

In [8]:
f.board.shape = (L//2, L)
print(f.board)

[[1 1 0 1 0 1 1 0]
 [0 1 0 1 0 1 0 0]
 [0 0 1 1 1 0 0 0]
 [0 0 0 1 0 0 0 0]]
