In [1]:
from classic_fib import FibCode
import numpy as np 

In [2]:
f = FibCode(4)

print(f" original code baord is  {f.original_code_board}")
print(f" error board is code {f.board}")
print(f" initial symmetry is: {f.fundamental_symmetry}")
print(f"fundamental_stabilizer_parity_check_matrix is : {f.fundamental_stabilizer_parity_check_matrix}")
print(f"fundamental_matching_graph is : {f.fundamental_matching_graph}")
print(f" Hx {f.Hx}")
print(f" Hy is code {f.Hy}")


 original code baord is  [0 0 1 0 0 1 1 1]
 error board is code [0 0 1 0 0 1 1 1]
 initial symmetry is: [0 0 1 0 0 1 1 1]
fundamental_stabilizer_parity_check_matrix is : [[0 1 1 1 0 0 1 0]
 [0 1 0 0 1 1 1 0]
 [0 0 1 0 0 1 1 1]
 [0 0 0 1 1 0 1 1]]
fundamental_matching_graph is : {(2, 3, 6), (1, 3, 4), (0, 3, 3), (0, 1, 6), (1, 2, 5), (2, 3, 7), (0, 2, 2), (0, 1, 1)}
 Hx [[0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]]
 Hy is code [[0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]


In [3]:
f.fundamental_matching_graph

{(0, 1, 1),
 (0, 1, 6),
 (0, 2, 2),
 (0, 3, 3),
 (1, 2, 5),
 (1, 3, 4),
 (2, 3, 6),
 (2, 3, 7)}

In [ ]:
f.fundamental_stabilizer_parity_check_matrix