In [1]:
from classic_fib import FibCode
import numpy as np 

In [2]:
L = 4
f = FibCode(L)
input = np.array(list(range((L**2)//2)))

shiftby1 = np.array(list(range(L * (L//2 - 1), L * (L//2 ))))
shiftby1 = np.append(shiftby1, np.array([np.array(list(range((L*row), ((L*row) + L)))) for row in range(0, (L//2) - 1)]))

In [4]:
answerby1 = f.shift_by_y(input, 1)

In [5]:
answerby1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
np.matmul(f.Hy, input)

array([4, 5, 6, 7, 0, 1, 2, 3])

In [15]:
powered = np.linalg.matrix_power(f.Hy,1% f.L//2 )
np.matmul(powered, input)

array([4, 5, 6, 7, 0, 1, 2, 3])

In [17]:
1% f.L//2


0