In [1]:
from classic_fib import FibCode
import numpy as np 

In [3]:
f = FibCode(4)

print(f" original code baord is  {f.original_code_board}")
print(f" error board is code {f.board}")
print(f" initial symmetry is: {f.fundamental_symmetry}")
print(f"fundamental_stabilizer_parity_check_matrix is : {f.fundamental_stabilizer_parity_check_matrix}")
print(f"fundamental_single_error_syndromes is : {f.fundamental_single_error_syndromes}")
print(f" Hx {f.Hx}")
print(f" Hy is code {f.Hy}")

f.decode_fib_code()


 original code baord is  [0 0 1 0 0 1 1 1]
 error board is code [0 0 1 0 0 1 1 1]
 initial symmetry is: [0 0 1 0 0 1 1 1]
fundamental_stabilizer_parity_check_matrix is : [[0 1 1 1 0 0 1 0]
 [0 1 0 0 1 1 1 0]
 [0 0 1 0 0 1 1 1]
 [0 0 0 1 1 0 1 1]]
fundamental_single_error_syndromes is : {(2, 3, 6), (1, 3, 4), (0, 3, 3), (0, 1, 6), (1, 2, 5), (2, 3, 7), (0, 2, 2), (0, 1, 1)}
 Hx [[0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]]
 Hy is code [[0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]


ValueError: The shape ((8,)) of the syndrome vector z is not valid.

In [ ]:
f.fundamental_matching_graph

In [ ]:
f.fundamental_stabilizer_parity_check_matrix