In [1]:
from classic_fib import FibCode
import numpy as np 


In [2]:
f = FibCode(4)
fundamental_stab_faces, fundamental_check_matrix, fund_error_pairs, fund_matching_graph = f.decode_fib_code()

In [3]:
print(fundamental_stab_faces)
print()
print(fundamental_check_matrix)
print()
for elem in sorted(list(fund_error_pairs),key=lambda x: x[-1]):
    print(elem)


[[0 1 0 0]
 [1 1 1 0]]

[[1 1 1 0 0 1 0 0]
 [1 0 0 0 1 1 0 1]
 [0 1 0 0 1 1 1 0]
 [0 0 1 0 0 1 1 1]]

(0, 1, 0)
(0, 2, 1)
(0, 3, 2)
(1, 2, 4)
(2, 3, 5)
(0, 1, 5)
(2, 3, 6)
(1, 3, 7)


In [16]:
fund_matching_graph.