In [28]:
from classic_fib import FibCode
import numpy as np 
import networkx as nx 

def pprint(matrix):
    print('\n'.join(['\t'.join([str(cell) for cell in row]) for row in matrix]))

In [36]:


L = 4
eboard = np.zeros((L**2)//2, dtype = int)
eboard[1:4] = 1
eboard[6] = 1 
eboard[4] = 1

f = FibCode(L, p=0, error_board_override=eboard)
f.original_errors_board.shape = (L//2, L)
matrix = f.original_errors_board
print(matrix)

[[0 1 1 1]
 [1 0 1 0]]


In [43]:
# f.decode_fib_code()
f.fundamental_single_error_syndromes
f.fundamental_symmetry.shape = (L//2,L)
pprint(f.fundamental_symmetry)
print()
pprint(f.fundamental_stabilizer_parity_check_matrix)

print(f.fundamental_stabilizer_parity_check_matrix)



0	1	0	0
1	1	1	0

1	1	1	0	0	1	0	0
1	0	0	0	1	1	0	1
0	1	0	0	1	1	1	0
0	0	1	0	0	1	1	1
[[1 1 1 0 0 1 0 0]
 [1 0 0 0 1 1 0 1]
 [0 1 0 0 1 1 1 0]
 [0 0 1 0 0 1 1 1]]


In [38]:
f.generate_all_possible_error_syndromes(f.fundamental_stabilizer_parity_check_matrix)

{(0, 1, 0),
 (0, 1, 5),
 (0, 2, 1),
 (0, 3, 2),
 (1, 2, 4),
 (1, 3, 7),
 (2, 3, 5),
 (2, 3, 6)}

In [39]:
f.original_code_board.shape = (L//2, L)
pprint(f.original_code_board)

0	0	0	0
0	0	0	0


In [40]:
f.decode_fib_code()

'yay!!'

In [41]:
f.board
f.original_errors_board



array([[0, 1, 1, 1],
       [1, 0, 1, 0]])