In [2]:
import numpy as np
import copy
from classic_fib import FibCode
import networkx as nx 
import rustworkx as rx 
def mprintboard(matrix, L= 4):
    if matrix.shape == ((L**2)//2,):
        matrix.shape = (L//2,L)
        print('\n'.join(['\t'.join([str(cell) for cell in row]) for row in matrix]))
        matrix.shape =  ((L**2)//2,)
    else:
        print('\n'.join(['\t'.join([str(cell) for cell in row]) for row in matrix])) 
    
def syn_meas(check_matrix, board):
    return np.matmul(check_matrix, board)%2
    

In [14]:
L=4
f = FibCode(L)
len(f.all_stabs_check_mat)
hori_stab_faces = copy.deepcopy(f.fundamental_symmetry)
verti_stab_faces = copy.deepcopy(f.fundamental_symmetry)
hori_stab_faces = f.shift_by_x(f.shift_by_y(hori_stab_faces),  power=(-f.L//2) + 1)
verti_stab_faces = f.shift_by_x(f.shift_by_y(hori_stab_faces))

hori_stab_faces.shape = (L//2,L)
verti_stab_faces.shape = (L//2,L)

hori_pairity_mat, _ = f.generate_check_matrix_from_faces(hori_stab_faces)
verti_pairity_mat,_ = f.generate_check_matrix_from_faces(verti_stab_faces)


In [15]:
print(hori_pairity_mat)

[[1 1 0 1 1 0 0 0]
 [1 1 1 0 0 1 0 0]
 [1 0 1 1 0 0 0 1]
 [1 0 0 0 1 1 0 1]]


In [16]:
for row in range(len(hori_pairity_mat)):
    hori_pairity_mat[row] = f.shift_by_x(hori_pairity_mat[row])
print(hori_pairity_mat)

[[1 1 1 0 0 1 0 0]
 [0 1 1 1 0 0 1 0]
 [1 1 0 1 1 0 0 0]
 [0 1 0 0 1 1 1 0]]
