In [1]:
from fib_code.classic_fib_code import ClassicFibCode
import numpy as np 
import copy


for L in [8,16]:
    for code_offset in range(0, L, L//4): # offset of the codeword 
        for error_offset in range(0,L,L//3):
            width = L//4 
            print(f"L is {L}, code_offset is {code_offset}, error_offset is {error_offset} and width is {width}")
            start_arr = np.zeros(L, dtype=int)
            start_arr[code_offset] = 1
            codeword = ClassicFibCode.generate_init_code_word(L, start_arr=start_arr)
            print("codeword")
            print(codeword)
            print()


            error_board = copy.deepcopy(codeword)
            error_board[:,error_offset:width + error_offset] = 1
            print("error board")
            print(error_board)
            f = ClassicFibCode(L=L, original_code_board=codeword, original_errors_board=error_board)
            res, info = f.decode_fib_code()
            print(res)
            print()

L is 8, code_offset is 0, error_offset is 0 and width is 2
codeword
[[1 0 1 1 0 1 1 0]
 [1 0 1 0 0 0 1 0]
 [1 1 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]]

error board
[[1 1 1 1 0 1 1 0]
 [1 1 1 0 0 0 1 0]
 [1 1 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0]]
yay! success

L is 8, code_offset is 0, error_offset is 2 and width is 2
codeword
[[1 0 1 1 0 1 1 0]
 [1 0 1 0 0 0 1 0]
 [1 1 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]]

error board
[[1 0 1 1 0 1 1 0]
 [1 0 1 1 0 0 1 0]
 [1 1 1 1 0 0 0 1]
 [1 0 1 1 0 0 0 0]]
yay! success

L is 8, code_offset is 0, error_offset is 4 and width is 2
codeword
[[1 0 1 1 0 1 1 0]
 [1 0 1 0 0 0 1 0]
 [1 1 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]]

error board
[[1 0 1 1 1 1 1 0]
 [1 0 1 0 1 1 1 0]
 [1 1 0 0 1 1 0 1]
 [1 0 0 0 1 1 0 0]]
yay! success

L is 8, code_offset is 0, error_offset is 6 and width is 2
codeword
[[1 0 1 1 0 1 1 0]
 [1 0 1 0 0 0 1 0]
 [1 1 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]]

error board
[[1 0 1 1 0 1 1 1]
 [1 0 1 0 0 0 1 1]
 [1 1 0 0 0 0 1 1]
 [1 0 0 0 0 0 1 1]]
yay! success

L is